# Generated by Django 5.0.1 on 2024-02-05 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='committee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='theses', to='theses.committee'),
        ),
    ]
