# Generated by Django 5.0.1 on 2024-02-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0002_alter_thesis_committee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='lecturer',
            new_name='member',
        ),
    ]
